# App\Entity\Product:
#   properties:
#     Name:
#       - NotBlank: { message: "Le nom du produit est obligatoire" }
#       - Length: { min: 3, max: 255, minMessage: "Le nom du produit doit faire plus de 3 carac" }
#     price:
#       - NotBlank: { message: "Le prix du produit "}